apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bocas-ingress
  namespace: bocas
spec:
  rules:
  - host: 100bocas.cabrasky.net
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: bocas-backend
            port:
              number: 8112
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: bocas-backend
            port:
              number: 8112
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bocas-frontend
            port:
              number: 8120
