apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bocas

resources:
- ../../base

images:
- name: PLACEHOLDER_BACKEND
  newName: 192.168.1.11:5000/bocas-backend
  newTag: latest
- name: PLACEHOLDER_FRONTEND
  newName: 192.168.1.11:5000/bocas-frontend
  newTag: latest

patches:
- path: patches/backend-replicas.yaml
- path: patches/frontend-replicas.yaml
- path: patches/host-ingress.yaml
