apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bocas-ingress
  namespace: bocas
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: OVERLAY_PATCH_REQUIRED
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: bocas-backend
            port:
              number: 8112
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: bocas-backend
            port:
              number: 8112
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bocas-frontend
            port:
              number: 8120
