apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bocas

resources:
- namespace.yaml
- secrets.yaml
- ingress.yaml
- init-sql-cm.yaml
- database.yaml
- backend.yaml
- frontend.yaml
- pdbs.yaml
