apiVersion: v1
kind: Secret
metadata:
  name: bocas-secrets
  namespace: bocas
type: Opaque
stringData:
  BOCAS_ADMIN_PASSWORD: "CP^sc@XbD6SH"
  BOCAS_ADMIN_SERVER_SECRET: "CHANGE_ME_FIRST_DEPLOY"
  POSTGRES_USER: "bocas"
  POSTGRES_PASSWORD: "bocas_secret_k8s"
  POSTGRES_DB: "100bocas"
  BOCAS_DB: "postgresql://bocas:bocas_secret_k8s@bocas-db:5432/100bocas"
