apiVersion: v1
kind: Secret
metadata:
  name: bocas-secrets
  namespace: bocas
type: Opaque
stringData:
  BOCAS_ADMIN_PASSWORD: "CHANGE_ME_IN_JENKINS"
  POSTGRES_USER: "bocas"
  POSTGRES_PASSWORD: "***"
  POSTGRES_DB: "100bocas"
  BOCAS_DB: "postgresql://bocas:***@bocas-db:5432/100bocas"
